version: "3"
services:
  web:
    image: nginx
    volumes:
      - ".:/app"
      - "./docker_dev/nginx/site.conf:/etc/nginx/conf.d/default.conf"
      - "./docker_dev/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    depends_on:
      - php
    ports:
      - "80:80"

  php:
    build:
      context: .
      dockerfile: docker_dev/Dockerfile
    volumes:
      - ".:/app"
      - "./docker_dev/php.ini:/usr/local/etc/php/conf.d/custom.ini"
